// Auto-generated OpenCL dlopen-redirect shim — 119 functions
// Bridges to the real vendor Adreno driver (libOpenCL.so in /vendor/lib64) at runtime
// via dlopen("libOpenCL.so", ...) + dlsym, so the app can statically link against
// the OpenCL ABI without bundling proprietary vendor code.
//
// Generated by gen_shim.py from opencl-headers/CL/cl_function_types.h. To rebuild
// (e.g. after updating headers), regenerate via gen_shim.py and recompile with the
// NDK aarch64 clang as a SHARED lib with -Wl,-soname,libOpenCL.so, replacing
// ../opencl-stub/libOpenCL.so. See CMakeLists.txt for how it's linked/packaged.
#include <dlfcn.h>
#include <android/log.h>
#include <time.h>
#include <string.h>
#include <stdatomic.h>
#define CL_TARGET_OPENCL_VERSION 300
#include <CL/cl.h>
#include <CL/cl_ext.h>
// NOTE: cl_function_types.h is NOT included — it declares typedefs for newer
// QCOM perf-monitor/recording/EGL extensions whose types our header snapshot
// lacks. We declare our own _t typedefs below for just the functions we shim.

#define TAG "OpenCLShim"

// ── Diagnostic timing instrumentation ────────────────────────────────────
// Added to pin down where the ~25min OpenCL model-load hang comes from
// (suspected: dozens of clCreateProgramWithSource+clBuildProgram JIT compiles
// of embedded Adreno kernels, vs. Vulkan's precompiled SPIR-V). Logs go to
// logcat tag "OpenCLShim" so `adb logcat -s OpenCLShim` captures everything.
static long long now_ms() {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (long long)ts.tv_sec * 1000 + ts.tv_nsec / 1000000;
}
static atomic_int g_build_count = 0;
static atomic_int g_program_count = 0;
static atomic_llong g_build_total_ms = 0;

static void* real_handle() {
    static void* h = []() -> void* {
        // IMPORTANT: must dlopen the vendor driver by ABSOLUTE PATH, not bare name.
        // A bare-name dlopen("libOpenCL.so", ...) resolves via soname matching in the
        // app's linker namespace — which finds THIS shim's own already-loaded instance
        // (it shares the same soname to satisfy static DT_NEEDED linking), producing
        // infinite self-recursion on every OpenCL call (dlsym returns our own wrappers).
        // Loading by absolute path bypasses soname resolution and grabs the real driver.
        const char* candidates[] = {
            "/vendor/lib64/libOpenCL_adreno.so",
            "/vendor/lib64/libOpenCL.so",
        };
        void* h = nullptr;
        for (const char* path : candidates) {
            h = dlopen(path, RTLD_NOW | RTLD_LOCAL);
            __android_log_print(h ? ANDROID_LOG_INFO : ANDROID_LOG_WARN, TAG,
                                "real driver dlopen(%s) %s: %s", path, h ? "OK" : "failed", dlerror());
            if (h) break;
        }
        if (!h) {
            __android_log_print(ANDROID_LOG_ERROR, TAG, "real driver dlopen: ALL candidates failed");
        }
        return h;
    }();
    return h;
}

static void* resolve(const char* name) {
    void* h = real_handle();
    if (!h) return nullptr;
    void* sym = dlsym(h, name);
    if (!sym) __android_log_print(ANDROID_LOG_WARN, TAG, "missing symbol: %s", name);
    return sym;
}

extern "C" {

typedef cl_int (CL_API_CALL *clGetPlatformIDs_fn_t)(cl_uint num_entries, cl_platform_id* platforms, cl_uint* num_platforms);
CL_API_ENTRY cl_int CL_API_CALL clGetPlatformIDs(cl_uint num_entries, cl_platform_id* platforms, cl_uint* num_platforms) {
    using fn_t = clGetPlatformIDs_fn_t;
    static fn_t fn = (fn_t)resolve("clGetPlatformIDs");
    if (!fn) return (cl_int)0;
    __android_log_print(ANDROID_LOG_INFO, TAG, "clGetPlatformIDs BEGIN (first real driver call — may trigger driver lazy-init)");
    long long t0 = now_ms();
    cl_int r = fn(num_entries, platforms, num_platforms);
    __android_log_print(ANDROID_LOG_INFO, TAG,
        "clGetPlatformIDs END   err=%d num_platforms=%u elapsed_ms=%lld",
        (int)r, num_platforms ? *num_platforms : 0, now_ms() - t0);
    return r;
}

typedef cl_int (CL_API_CALL *clGetPlatformInfo_fn_t)(cl_platform_id platform, cl_platform_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret);
CL_API_ENTRY cl_int CL_API_CALL clGetPlatformInfo(cl_platform_id platform, cl_platform_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret) {
    using fn_t = clGetPlatformInfo_fn_t;
    static fn_t fn = (fn_t)resolve("clGetPlatformInfo");
    if (!fn) return (cl_int)0;
    long long t0 = now_ms();
    cl_int r = fn(platform, param_name, param_value_size, param_value, param_value_size_ret);
    long long el = now_ms() - t0;
    if (el > 5) __android_log_print(ANDROID_LOG_INFO, TAG, "clGetPlatformInfo param=%u elapsed_ms=%lld (slow)", (unsigned)param_name, el);
    return r;
}

typedef cl_int (CL_API_CALL *clGetDeviceIDs_fn_t)(cl_platform_id platform, cl_device_type device_type, cl_uint num_entries, cl_device_id* devices, cl_uint* num_devices);
CL_API_ENTRY cl_int CL_API_CALL clGetDeviceIDs(cl_platform_id platform, cl_device_type device_type, cl_uint num_entries, cl_device_id* devices, cl_uint* num_devices) {
    using fn_t = clGetDeviceIDs_fn_t;
    static fn_t fn = (fn_t)resolve("clGetDeviceIDs");
    if (!fn) return (cl_int)0;
    long long t0 = now_ms();
    cl_int r = fn(platform, device_type, num_entries, devices, num_devices);
    __android_log_print(ANDROID_LOG_INFO, TAG,
        "clGetDeviceIDs err=%d num_devices=%u elapsed_ms=%lld",
        (int)r, num_devices ? *num_devices : 0, now_ms() - t0);
    return r;
}

typedef cl_int (CL_API_CALL *clGetDeviceInfo_fn_t)(cl_device_id device, cl_device_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret);
CL_API_ENTRY cl_int CL_API_CALL clGetDeviceInfo(cl_device_id device, cl_device_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret) {
    using fn_t = clGetDeviceInfo_fn_t;
    static fn_t fn = (fn_t)resolve("clGetDeviceInfo");
    if (!fn) return (cl_int)0;
    long long t0 = now_ms();
    cl_int rr = fn(device, param_name, param_value_size, param_value, param_value_size_ret);
    long long el = now_ms() - t0;
    if (el > 5) __android_log_print(ANDROID_LOG_INFO, TAG, "clGetDeviceInfo param=%u elapsed_ms=%lld (slow)", (unsigned)param_name, el);
    return rr;
}

typedef cl_context (CL_API_CALL *clCreateContext_fn_t)(const cl_context_properties* properties, cl_uint num_devices, const cl_device_id* devices, void (CL_CALLBACK* pfn_notify)(const char* errinfo, const void* private_info, size_t cb, void* user_data), void* user_data, cl_int* errcode_ret);
CL_API_ENTRY cl_context CL_API_CALL clCreateContext(const cl_context_properties* properties, cl_uint num_devices, const cl_device_id* devices, void (CL_CALLBACK* pfn_notify)(const char* errinfo, const void* private_info, size_t cb, void* user_data), void* user_data, cl_int* errcode_ret) {
    using fn_t = clCreateContext_fn_t;
    static fn_t fn = (fn_t)resolve("clCreateContext");
    if (!fn) return (cl_context)0;
    long long t0 = now_ms();
    cl_context c = fn(properties, num_devices, devices, pfn_notify, user_data, errcode_ret);
    __android_log_print(ANDROID_LOG_INFO, TAG,
        "clCreateContext: num_devices=%u -> context=%p elapsed_ms=%lld",
        num_devices, (void*)c, now_ms() - t0);
    return c;
}

typedef cl_context (CL_API_CALL *clCreateContextFromType_fn_t)(const cl_context_properties* properties, cl_device_type device_type, void (CL_CALLBACK* pfn_notify)(const char* errinfo, const void* private_info, size_t cb, void* user_data), void* user_data, cl_int* errcode_ret);
CL_API_ENTRY cl_context CL_API_CALL clCreateContextFromType(const cl_context_properties* properties, cl_device_type device_type, void (CL_CALLBACK* pfn_notify)(const char* errinfo, const void* private_info, size_t cb, void* user_data), void* user_data, cl_int* errcode_ret) {
    using fn_t = clCreateContextFromType_fn_t;
    static fn_t fn = (fn_t)resolve("clCreateContextFromType");
    if (!fn) return (cl_context)0;
    return fn(properties, device_type, pfn_notify, user_data, errcode_ret);
}

typedef cl_int (CL_API_CALL *clRetainContext_fn_t)(cl_context context);
CL_API_ENTRY cl_int CL_API_CALL clRetainContext(cl_context context) {
    using fn_t = clRetainContext_fn_t;
    static fn_t fn = (fn_t)resolve("clRetainContext");
    if (!fn) return (cl_int)0;
    return fn(context);
}

typedef cl_int (CL_API_CALL *clReleaseContext_fn_t)(cl_context context);
CL_API_ENTRY cl_int CL_API_CALL clReleaseContext(cl_context context) {
    using fn_t = clReleaseContext_fn_t;
    static fn_t fn = (fn_t)resolve("clReleaseContext");
    if (!fn) return (cl_int)0;
    return fn(context);
}

typedef cl_int (CL_API_CALL *clGetContextInfo_fn_t)(cl_context context, cl_context_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret);
CL_API_ENTRY cl_int CL_API_CALL clGetContextInfo(cl_context context, cl_context_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret) {
    using fn_t = clGetContextInfo_fn_t;
    static fn_t fn = (fn_t)resolve("clGetContextInfo");
    if (!fn) return (cl_int)0;
    return fn(context, param_name, param_value_size, param_value, param_value_size_ret);
}

typedef cl_int (CL_API_CALL *clRetainCommandQueue_fn_t)(cl_command_queue command_queue);
CL_API_ENTRY cl_int CL_API_CALL clRetainCommandQueue(cl_command_queue command_queue) {
    using fn_t = clRetainCommandQueue_fn_t;
    static fn_t fn = (fn_t)resolve("clRetainCommandQueue");
    if (!fn) return (cl_int)0;
    return fn(command_queue);
}

typedef cl_int (CL_API_CALL *clReleaseCommandQueue_fn_t)(cl_command_queue command_queue);
CL_API_ENTRY cl_int CL_API_CALL clReleaseCommandQueue(cl_command_queue command_queue) {
    using fn_t = clReleaseCommandQueue_fn_t;
    static fn_t fn = (fn_t)resolve("clReleaseCommandQueue");
    if (!fn) return (cl_int)0;
    return fn(command_queue);
}

typedef cl_int (CL_API_CALL *clGetCommandQueueInfo_fn_t)(cl_command_queue command_queue, cl_command_queue_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret);
CL_API_ENTRY cl_int CL_API_CALL clGetCommandQueueInfo(cl_command_queue command_queue, cl_command_queue_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret) {
    using fn_t = clGetCommandQueueInfo_fn_t;
    static fn_t fn = (fn_t)resolve("clGetCommandQueueInfo");
    if (!fn) return (cl_int)0;
    return fn(command_queue, param_name, param_value_size, param_value, param_value_size_ret);
}

typedef cl_mem (CL_API_CALL *clCreateBuffer_fn_t)(cl_context context, cl_mem_flags flags, size_t size, void* host_ptr, cl_int* errcode_ret);
CL_API_ENTRY cl_mem CL_API_CALL clCreateBuffer(cl_context context, cl_mem_flags flags, size_t size, void* host_ptr, cl_int* errcode_ret) {
    using fn_t = clCreateBuffer_fn_t;
    static fn_t fn = (fn_t)resolve("clCreateBuffer");
    if (!fn) return (cl_mem)0;
    return fn(context, flags, size, host_ptr, errcode_ret);
}

typedef cl_int (CL_API_CALL *clRetainMemObject_fn_t)(cl_mem memobj);
CL_API_ENTRY cl_int CL_API_CALL clRetainMemObject(cl_mem memobj) {
    using fn_t = clRetainMemObject_fn_t;
    static fn_t fn = (fn_t)resolve("clRetainMemObject");
    if (!fn) return (cl_int)0;
    return fn(memobj);
}

typedef cl_int (CL_API_CALL *clReleaseMemObject_fn_t)(cl_mem memobj);
CL_API_ENTRY cl_int CL_API_CALL clReleaseMemObject(cl_mem memobj) {
    using fn_t = clReleaseMemObject_fn_t;
    static fn_t fn = (fn_t)resolve("clReleaseMemObject");
    if (!fn) return (cl_int)0;
    return fn(memobj);
}

typedef cl_int (CL_API_CALL *clGetSupportedImageFormats_fn_t)(cl_context context, cl_mem_flags flags, cl_mem_object_type image_type, cl_uint num_entries, cl_image_format* image_formats, cl_uint* num_image_formats);
CL_API_ENTRY cl_int CL_API_CALL clGetSupportedImageFormats(cl_context context, cl_mem_flags flags, cl_mem_object_type image_type, cl_uint num_entries, cl_image_format* image_formats, cl_uint* num_image_formats) {
    using fn_t = clGetSupportedImageFormats_fn_t;
    static fn_t fn = (fn_t)resolve("clGetSupportedImageFormats");
    if (!fn) return (cl_int)0;
    return fn(context, flags, image_type, num_entries, image_formats, num_image_formats);
}

typedef cl_int (CL_API_CALL *clGetMemObjectInfo_fn_t)(cl_mem memobj, cl_mem_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret);
CL_API_ENTRY cl_int CL_API_CALL clGetMemObjectInfo(cl_mem memobj, cl_mem_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret) {
    using fn_t = clGetMemObjectInfo_fn_t;
    static fn_t fn = (fn_t)resolve("clGetMemObjectInfo");
    if (!fn) return (cl_int)0;
    return fn(memobj, param_name, param_value_size, param_value, param_value_size_ret);
}

typedef cl_int (CL_API_CALL *clGetImageInfo_fn_t)(cl_mem image, cl_image_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret);
CL_API_ENTRY cl_int CL_API_CALL clGetImageInfo(cl_mem image, cl_image_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret) {
    using fn_t = clGetImageInfo_fn_t;
    static fn_t fn = (fn_t)resolve("clGetImageInfo");
    if (!fn) return (cl_int)0;
    return fn(image, param_name, param_value_size, param_value, param_value_size_ret);
}

typedef cl_int (CL_API_CALL *clRetainSampler_fn_t)(cl_sampler sampler);
CL_API_ENTRY cl_int CL_API_CALL clRetainSampler(cl_sampler sampler) {
    using fn_t = clRetainSampler_fn_t;
    static fn_t fn = (fn_t)resolve("clRetainSampler");
    if (!fn) return (cl_int)0;
    return fn(sampler);
}

typedef cl_int (CL_API_CALL *clReleaseSampler_fn_t)(cl_sampler sampler);
CL_API_ENTRY cl_int CL_API_CALL clReleaseSampler(cl_sampler sampler) {
    using fn_t = clReleaseSampler_fn_t;
    static fn_t fn = (fn_t)resolve("clReleaseSampler");
    if (!fn) return (cl_int)0;
    return fn(sampler);
}

typedef cl_int (CL_API_CALL *clGetSamplerInfo_fn_t)(cl_sampler sampler, cl_sampler_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret);
CL_API_ENTRY cl_int CL_API_CALL clGetSamplerInfo(cl_sampler sampler, cl_sampler_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret) {
    using fn_t = clGetSamplerInfo_fn_t;
    static fn_t fn = (fn_t)resolve("clGetSamplerInfo");
    if (!fn) return (cl_int)0;
    return fn(sampler, param_name, param_value_size, param_value, param_value_size_ret);
}

typedef cl_program (CL_API_CALL *clCreateProgramWithSource_fn_t)(cl_context context, cl_uint count, const char** strings, const size_t* lengths, cl_int* errcode_ret);
CL_API_ENTRY cl_program CL_API_CALL clCreateProgramWithSource(cl_context context, cl_uint count, const char** strings, const size_t* lengths, cl_int* errcode_ret) {
    using fn_t = clCreateProgramWithSource_fn_t;
    static fn_t fn = (fn_t)resolve("clCreateProgramWithSource");
    if (!fn) return (cl_program)0;
    size_t total_len = 0;
    for (cl_uint i = 0; i < count; i++) {
        total_len += (lengths && lengths[i]) ? lengths[i] : (strings && strings[i] ? strlen(strings[i]) : 0);
    }
    int idx = atomic_fetch_add(&g_program_count, 1);
    cl_program p = fn(context, count, strings, lengths, errcode_ret);
    __android_log_print(ANDROID_LOG_INFO, TAG,
        "clCreateProgramWithSource[#%d]: count=%u total_src_bytes=%zu -> program=%p",
        idx, count, total_len, (void*)p);
    return p;
}

typedef cl_program (CL_API_CALL *clCreateProgramWithBinary_fn_t)(cl_context context, cl_uint num_devices, const cl_device_id* device_list, const size_t* lengths, const unsigned char** binaries, cl_int* binary_status, cl_int* errcode_ret);
CL_API_ENTRY cl_program CL_API_CALL clCreateProgramWithBinary(cl_context context, cl_uint num_devices, const cl_device_id* device_list, const size_t* lengths, const unsigned char** binaries, cl_int* binary_status, cl_int* errcode_ret) {
    using fn_t = clCreateProgramWithBinary_fn_t;
    static fn_t fn = (fn_t)resolve("clCreateProgramWithBinary");
    if (!fn) return (cl_program)0;
    return fn(context, num_devices, device_list, lengths, binaries, binary_status, errcode_ret);
}

typedef cl_int (CL_API_CALL *clRetainProgram_fn_t)(cl_program program);
CL_API_ENTRY cl_int CL_API_CALL clRetainProgram(cl_program program) {
    using fn_t = clRetainProgram_fn_t;
    static fn_t fn = (fn_t)resolve("clRetainProgram");
    if (!fn) return (cl_int)0;
    return fn(program);
}

typedef cl_int (CL_API_CALL *clReleaseProgram_fn_t)(cl_program program);
CL_API_ENTRY cl_int CL_API_CALL clReleaseProgram(cl_program program) {
    using fn_t = clReleaseProgram_fn_t;
    static fn_t fn = (fn_t)resolve("clReleaseProgram");
    if (!fn) return (cl_int)0;
    return fn(program);
}

typedef cl_int (CL_API_CALL *clBuildProgram_fn_t)(cl_program program, cl_uint num_devices, const cl_device_id* device_list, const char* options, void (CL_CALLBACK* pfn_notify)(cl_program program, void* user_data), void* user_data);
CL_API_ENTRY cl_int CL_API_CALL clBuildProgram(cl_program program, cl_uint num_devices, const cl_device_id* device_list, const char* options, void (CL_CALLBACK* pfn_notify)(cl_program program, void* user_data), void* user_data) {
    using fn_t = clBuildProgram_fn_t;
    static fn_t fn = (fn_t)resolve("clBuildProgram");
    if (!fn) return (cl_int)0;
    int idx = atomic_fetch_add(&g_build_count, 1);
    long long t0 = now_ms();
    __android_log_print(ANDROID_LOG_INFO, TAG,
        "clBuildProgram[#%d] BEGIN program=%p options=\"%s\"",
        idx, (void*)program, options ? options : "");
    cl_int err = fn(program, num_devices, device_list, options, pfn_notify, user_data);
    long long elapsed = now_ms() - t0;
    long long total = atomic_fetch_add(&g_build_total_ms, elapsed) + elapsed;
    __android_log_print(ANDROID_LOG_INFO, TAG,
        "clBuildProgram[#%d] END   program=%p err=%d elapsed_ms=%lld running_total_ms=%lld",
        idx, (void*)program, (int)err, elapsed, total);
    return err;
}

typedef cl_int (CL_API_CALL *clGetProgramInfo_fn_t)(cl_program program, cl_program_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret);
CL_API_ENTRY cl_int CL_API_CALL clGetProgramInfo(cl_program program, cl_program_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret) {
    using fn_t = clGetProgramInfo_fn_t;
    static fn_t fn = (fn_t)resolve("clGetProgramInfo");
    if (!fn) return (cl_int)0;
    return fn(program, param_name, param_value_size, param_value, param_value_size_ret);
}

typedef cl_int (CL_API_CALL *clGetProgramBuildInfo_fn_t)(cl_program program, cl_device_id device, cl_program_build_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret);
CL_API_ENTRY cl_int CL_API_CALL clGetProgramBuildInfo(cl_program program, cl_device_id device, cl_program_build_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret) {
    using fn_t = clGetProgramBuildInfo_fn_t;
    static fn_t fn = (fn_t)resolve("clGetProgramBuildInfo");
    if (!fn) return (cl_int)0;
    return fn(program, device, param_name, param_value_size, param_value, param_value_size_ret);
}

typedef cl_kernel (CL_API_CALL *clCreateKernel_fn_t)(cl_program program, const char* kernel_name, cl_int* errcode_ret);
CL_API_ENTRY cl_kernel CL_API_CALL clCreateKernel(cl_program program, const char* kernel_name, cl_int* errcode_ret) {
    using fn_t = clCreateKernel_fn_t;
    static fn_t fn = (fn_t)resolve("clCreateKernel");
    if (!fn) return (cl_kernel)0;
    return fn(program, kernel_name, errcode_ret);
}

typedef cl_int (CL_API_CALL *clCreateKernelsInProgram_fn_t)(cl_program program, cl_uint num_kernels, cl_kernel* kernels, cl_uint* num_kernels_ret);
CL_API_ENTRY cl_int CL_API_CALL clCreateKernelsInProgram(cl_program program, cl_uint num_kernels, cl_kernel* kernels, cl_uint* num_kernels_ret) {
    using fn_t = clCreateKernelsInProgram_fn_t;
    static fn_t fn = (fn_t)resolve("clCreateKernelsInProgram");
    if (!fn) return (cl_int)0;
    return fn(program, num_kernels, kernels, num_kernels_ret);
}

typedef cl_int (CL_API_CALL *clRetainKernel_fn_t)(cl_kernel kernel);
CL_API_ENTRY cl_int CL_API_CALL clRetainKernel(cl_kernel kernel) {
    using fn_t = clRetainKernel_fn_t;
    static fn_t fn = (fn_t)resolve("clRetainKernel");
    if (!fn) return (cl_int)0;
    return fn(kernel);
}

typedef cl_int (CL_API_CALL *clReleaseKernel_fn_t)(cl_kernel kernel);
CL_API_ENTRY cl_int CL_API_CALL clReleaseKernel(cl_kernel kernel) {
    using fn_t = clReleaseKernel_fn_t;
    static fn_t fn = (fn_t)resolve("clReleaseKernel");
    if (!fn) return (cl_int)0;
    return fn(kernel);
}

typedef cl_int (CL_API_CALL *clSetKernelArg_fn_t)(cl_kernel kernel, cl_uint arg_index, size_t arg_size, const void* arg_value);
CL_API_ENTRY cl_int CL_API_CALL clSetKernelArg(cl_kernel kernel, cl_uint arg_index, size_t arg_size, const void* arg_value) {
    using fn_t = clSetKernelArg_fn_t;
    static fn_t fn = (fn_t)resolve("clSetKernelArg");
    if (!fn) return (cl_int)0;
    return fn(kernel, arg_index, arg_size, arg_value);
}

typedef cl_int (CL_API_CALL *clGetKernelInfo_fn_t)(cl_kernel kernel, cl_kernel_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret);
CL_API_ENTRY cl_int CL_API_CALL clGetKernelInfo(cl_kernel kernel, cl_kernel_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret) {
    using fn_t = clGetKernelInfo_fn_t;
    static fn_t fn = (fn_t)resolve("clGetKernelInfo");
    if (!fn) return (cl_int)0;
    return fn(kernel, param_name, param_value_size, param_value, param_value_size_ret);
}

typedef cl_int (CL_API_CALL *clGetKernelWorkGroupInfo_fn_t)(cl_kernel kernel, cl_device_id device, cl_kernel_work_group_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret);
CL_API_ENTRY cl_int CL_API_CALL clGetKernelWorkGroupInfo(cl_kernel kernel, cl_device_id device, cl_kernel_work_group_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret) {
    using fn_t = clGetKernelWorkGroupInfo_fn_t;
    static fn_t fn = (fn_t)resolve("clGetKernelWorkGroupInfo");
    if (!fn) return (cl_int)0;
    return fn(kernel, device, param_name, param_value_size, param_value, param_value_size_ret);
}

typedef cl_int (CL_API_CALL *clWaitForEvents_fn_t)(cl_uint num_events, const cl_event* event_list);
CL_API_ENTRY cl_int CL_API_CALL clWaitForEvents(cl_uint num_events, const cl_event* event_list) {
    using fn_t = clWaitForEvents_fn_t;
    static fn_t fn = (fn_t)resolve("clWaitForEvents");
    if (!fn) return (cl_int)0;
    return fn(num_events, event_list);
}

typedef cl_int (CL_API_CALL *clGetEventInfo_fn_t)(cl_event event, cl_event_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret);
CL_API_ENTRY cl_int CL_API_CALL clGetEventInfo(cl_event event, cl_event_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret) {
    using fn_t = clGetEventInfo_fn_t;
    static fn_t fn = (fn_t)resolve("clGetEventInfo");
    if (!fn) return (cl_int)0;
    return fn(event, param_name, param_value_size, param_value, param_value_size_ret);
}

typedef cl_int (CL_API_CALL *clRetainEvent_fn_t)(cl_event event);
CL_API_ENTRY cl_int CL_API_CALL clRetainEvent(cl_event event) {
    using fn_t = clRetainEvent_fn_t;
    static fn_t fn = (fn_t)resolve("clRetainEvent");
    if (!fn) return (cl_int)0;
    return fn(event);
}

typedef cl_int (CL_API_CALL *clReleaseEvent_fn_t)(cl_event event);
CL_API_ENTRY cl_int CL_API_CALL clReleaseEvent(cl_event event) {
    using fn_t = clReleaseEvent_fn_t;
    static fn_t fn = (fn_t)resolve("clReleaseEvent");
    if (!fn) return (cl_int)0;
    return fn(event);
}

typedef cl_int (CL_API_CALL *clGetEventProfilingInfo_fn_t)(cl_event event, cl_profiling_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret);
CL_API_ENTRY cl_int CL_API_CALL clGetEventProfilingInfo(cl_event event, cl_profiling_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret) {
    using fn_t = clGetEventProfilingInfo_fn_t;
    static fn_t fn = (fn_t)resolve("clGetEventProfilingInfo");
    if (!fn) return (cl_int)0;
    return fn(event, param_name, param_value_size, param_value, param_value_size_ret);
}

typedef cl_int (CL_API_CALL *clFlush_fn_t)(cl_command_queue command_queue);
CL_API_ENTRY cl_int CL_API_CALL clFlush(cl_command_queue command_queue) {
    using fn_t = clFlush_fn_t;
    static fn_t fn = (fn_t)resolve("clFlush");
    if (!fn) return (cl_int)0;
    return fn(command_queue);
}

typedef cl_int (CL_API_CALL *clFinish_fn_t)(cl_command_queue command_queue);
CL_API_ENTRY cl_int CL_API_CALL clFinish(cl_command_queue command_queue) {
    using fn_t = clFinish_fn_t;
    static fn_t fn = (fn_t)resolve("clFinish");
    if (!fn) return (cl_int)0;
    return fn(command_queue);
}

typedef cl_int (CL_API_CALL *clEnqueueReadBuffer_fn_t)(cl_command_queue command_queue, cl_mem buffer, cl_bool blocking_read, size_t offset, size_t size, void* ptr, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueReadBuffer(cl_command_queue command_queue, cl_mem buffer, cl_bool blocking_read, size_t offset, size_t size, void* ptr, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueReadBuffer_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueReadBuffer");
    if (!fn) return (cl_int)0;
    return fn(command_queue, buffer, blocking_read, offset, size, ptr, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clEnqueueWriteBuffer_fn_t)(cl_command_queue command_queue, cl_mem buffer, cl_bool blocking_write, size_t offset, size_t size, const void* ptr, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueWriteBuffer(cl_command_queue command_queue, cl_mem buffer, cl_bool blocking_write, size_t offset, size_t size, const void* ptr, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueWriteBuffer_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueWriteBuffer");
    if (!fn) return (cl_int)0;
    return fn(command_queue, buffer, blocking_write, offset, size, ptr, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clEnqueueCopyBuffer_fn_t)(cl_command_queue command_queue, cl_mem src_buffer, cl_mem dst_buffer, size_t src_offset, size_t dst_offset, size_t size, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueCopyBuffer(cl_command_queue command_queue, cl_mem src_buffer, cl_mem dst_buffer, size_t src_offset, size_t dst_offset, size_t size, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueCopyBuffer_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueCopyBuffer");
    if (!fn) return (cl_int)0;
    return fn(command_queue, src_buffer, dst_buffer, src_offset, dst_offset, size, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clEnqueueReadImage_fn_t)(cl_command_queue command_queue, cl_mem image, cl_bool blocking_read, const size_t* origin, const size_t* region, size_t row_pitch, size_t slice_pitch, void* ptr, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueReadImage(cl_command_queue command_queue, cl_mem image, cl_bool blocking_read, const size_t* origin, const size_t* region, size_t row_pitch, size_t slice_pitch, void* ptr, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueReadImage_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueReadImage");
    if (!fn) return (cl_int)0;
    return fn(command_queue, image, blocking_read, origin, region, row_pitch, slice_pitch, ptr, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clEnqueueWriteImage_fn_t)(cl_command_queue command_queue, cl_mem image, cl_bool blocking_write, const size_t* origin, const size_t* region, size_t input_row_pitch, size_t input_slice_pitch, const void* ptr, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueWriteImage(cl_command_queue command_queue, cl_mem image, cl_bool blocking_write, const size_t* origin, const size_t* region, size_t input_row_pitch, size_t input_slice_pitch, const void* ptr, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueWriteImage_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueWriteImage");
    if (!fn) return (cl_int)0;
    return fn(command_queue, image, blocking_write, origin, region, input_row_pitch, input_slice_pitch, ptr, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clEnqueueCopyImage_fn_t)(cl_command_queue command_queue, cl_mem src_image, cl_mem dst_image, const size_t* src_origin, const size_t* dst_origin, const size_t* region, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueCopyImage(cl_command_queue command_queue, cl_mem src_image, cl_mem dst_image, const size_t* src_origin, const size_t* dst_origin, const size_t* region, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueCopyImage_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueCopyImage");
    if (!fn) return (cl_int)0;
    return fn(command_queue, src_image, dst_image, src_origin, dst_origin, region, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clEnqueueCopyImageToBuffer_fn_t)(cl_command_queue command_queue, cl_mem src_image, cl_mem dst_buffer, const size_t* src_origin, const size_t* region, size_t dst_offset, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueCopyImageToBuffer(cl_command_queue command_queue, cl_mem src_image, cl_mem dst_buffer, const size_t* src_origin, const size_t* region, size_t dst_offset, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueCopyImageToBuffer_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueCopyImageToBuffer");
    if (!fn) return (cl_int)0;
    return fn(command_queue, src_image, dst_buffer, src_origin, region, dst_offset, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clEnqueueCopyBufferToImage_fn_t)(cl_command_queue command_queue, cl_mem src_buffer, cl_mem dst_image, size_t src_offset, const size_t* dst_origin, const size_t* region, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueCopyBufferToImage(cl_command_queue command_queue, cl_mem src_buffer, cl_mem dst_image, size_t src_offset, const size_t* dst_origin, const size_t* region, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueCopyBufferToImage_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueCopyBufferToImage");
    if (!fn) return (cl_int)0;
    return fn(command_queue, src_buffer, dst_image, src_offset, dst_origin, region, num_events_in_wait_list, event_wait_list, event);
}

typedef void* (CL_API_CALL *clEnqueueMapBuffer_fn_t)(cl_command_queue command_queue, cl_mem buffer, cl_bool blocking_map, cl_map_flags map_flags, size_t offset, size_t size, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event, cl_int* errcode_ret);
CL_API_ENTRY void* CL_API_CALL clEnqueueMapBuffer(cl_command_queue command_queue, cl_mem buffer, cl_bool blocking_map, cl_map_flags map_flags, size_t offset, size_t size, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event, cl_int* errcode_ret) {
    using fn_t = clEnqueueMapBuffer_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueMapBuffer");
    if (!fn) return (void*)0;
    return fn(command_queue, buffer, blocking_map, map_flags, offset, size, num_events_in_wait_list, event_wait_list, event, errcode_ret);
}

typedef void* (CL_API_CALL *clEnqueueMapImage_fn_t)(cl_command_queue command_queue, cl_mem image, cl_bool blocking_map, cl_map_flags map_flags, const size_t* origin, const size_t* region, size_t* image_row_pitch, size_t* image_slice_pitch, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event, cl_int* errcode_ret);
CL_API_ENTRY void* CL_API_CALL clEnqueueMapImage(cl_command_queue command_queue, cl_mem image, cl_bool blocking_map, cl_map_flags map_flags, const size_t* origin, const size_t* region, size_t* image_row_pitch, size_t* image_slice_pitch, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event, cl_int* errcode_ret) {
    using fn_t = clEnqueueMapImage_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueMapImage");
    if (!fn) return (void*)0;
    return fn(command_queue, image, blocking_map, map_flags, origin, region, image_row_pitch, image_slice_pitch, num_events_in_wait_list, event_wait_list, event, errcode_ret);
}

typedef cl_int (CL_API_CALL *clEnqueueUnmapMemObject_fn_t)(cl_command_queue command_queue, cl_mem memobj, void* mapped_ptr, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueUnmapMemObject(cl_command_queue command_queue, cl_mem memobj, void* mapped_ptr, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueUnmapMemObject_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueUnmapMemObject");
    if (!fn) return (cl_int)0;
    return fn(command_queue, memobj, mapped_ptr, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clEnqueueNDRangeKernel_fn_t)(cl_command_queue command_queue, cl_kernel kernel, cl_uint work_dim, const size_t* global_work_offset, const size_t* global_work_size, const size_t* local_work_size, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueNDRangeKernel(cl_command_queue command_queue, cl_kernel kernel, cl_uint work_dim, const size_t* global_work_offset, const size_t* global_work_size, const size_t* local_work_size, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueNDRangeKernel_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueNDRangeKernel");
    if (!fn) return (cl_int)0;
    return fn(command_queue, kernel, work_dim, global_work_offset, global_work_size, local_work_size, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clEnqueueNativeKernel_fn_t)(cl_command_queue command_queue, void (CL_CALLBACK* user_func)(void*), void* args, size_t cb_args, cl_uint num_mem_objects, const cl_mem* mem_list, const void** args_mem_loc, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueNativeKernel(cl_command_queue command_queue, void (CL_CALLBACK* user_func)(void*), void* args, size_t cb_args, cl_uint num_mem_objects, const cl_mem* mem_list, const void** args_mem_loc, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueNativeKernel_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueNativeKernel");
    if (!fn) return (cl_int)0;
    return fn(command_queue, user_func, args, cb_args, num_mem_objects, mem_list, args_mem_loc, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clSetCommandQueueProperty_fn_t)(cl_command_queue command_queue, cl_command_queue_properties properties, cl_bool enable, cl_command_queue_properties* old_properties);
CL_API_ENTRY cl_int CL_API_CALL clSetCommandQueueProperty(cl_command_queue command_queue, cl_command_queue_properties properties, cl_bool enable, cl_command_queue_properties* old_properties) {
    using fn_t = clSetCommandQueueProperty_fn_t;
    static fn_t fn = (fn_t)resolve("clSetCommandQueueProperty");
    if (!fn) return (cl_int)0;
    return fn(command_queue, properties, enable, old_properties);
}

typedef cl_mem (CL_API_CALL *clCreateImage2D_fn_t)(cl_context context, cl_mem_flags flags, const cl_image_format* image_format, size_t image_width, size_t image_height, size_t image_row_pitch, void* host_ptr, cl_int* errcode_ret);
CL_API_ENTRY cl_mem CL_API_CALL clCreateImage2D(cl_context context, cl_mem_flags flags, const cl_image_format* image_format, size_t image_width, size_t image_height, size_t image_row_pitch, void* host_ptr, cl_int* errcode_ret) {
    using fn_t = clCreateImage2D_fn_t;
    static fn_t fn = (fn_t)resolve("clCreateImage2D");
    if (!fn) return (cl_mem)0;
    return fn(context, flags, image_format, image_width, image_height, image_row_pitch, host_ptr, errcode_ret);
}

typedef cl_mem (CL_API_CALL *clCreateImage3D_fn_t)(cl_context context, cl_mem_flags flags, const cl_image_format* image_format, size_t image_width, size_t image_height, size_t image_depth, size_t image_row_pitch, size_t image_slice_pitch, void* host_ptr, cl_int* errcode_ret);
CL_API_ENTRY cl_mem CL_API_CALL clCreateImage3D(cl_context context, cl_mem_flags flags, const cl_image_format* image_format, size_t image_width, size_t image_height, size_t image_depth, size_t image_row_pitch, size_t image_slice_pitch, void* host_ptr, cl_int* errcode_ret) {
    using fn_t = clCreateImage3D_fn_t;
    static fn_t fn = (fn_t)resolve("clCreateImage3D");
    if (!fn) return (cl_mem)0;
    return fn(context, flags, image_format, image_width, image_height, image_depth, image_row_pitch, image_slice_pitch, host_ptr, errcode_ret);
}

typedef cl_int (CL_API_CALL *clEnqueueMarker_fn_t)(cl_command_queue command_queue, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueMarker(cl_command_queue command_queue, cl_event* event) {
    using fn_t = clEnqueueMarker_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueMarker");
    if (!fn) return (cl_int)0;
    return fn(command_queue, event);
}

typedef cl_int (CL_API_CALL *clEnqueueWaitForEvents_fn_t)(cl_command_queue command_queue, cl_uint num_events, const cl_event* event_list);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueWaitForEvents(cl_command_queue command_queue, cl_uint num_events, const cl_event* event_list) {
    using fn_t = clEnqueueWaitForEvents_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueWaitForEvents");
    if (!fn) return (cl_int)0;
    return fn(command_queue, num_events, event_list);
}

typedef cl_int (CL_API_CALL *clEnqueueBarrier_fn_t)(cl_command_queue command_queue);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueBarrier(cl_command_queue command_queue) {
    using fn_t = clEnqueueBarrier_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueBarrier");
    if (!fn) return (cl_int)0;
    return fn(command_queue);
}

typedef cl_int (CL_API_CALL *clUnloadCompiler_fn_t)(void);
CL_API_ENTRY cl_int CL_API_CALL clUnloadCompiler(void) {
    using fn_t = clUnloadCompiler_fn_t;
    static fn_t fn = (fn_t)resolve("clUnloadCompiler");
    if (!fn) return (cl_int)0;
    return fn();
}

typedef void* (CL_API_CALL *clGetExtensionFunctionAddress_fn_t)(const char* func_name);
CL_API_ENTRY void* CL_API_CALL clGetExtensionFunctionAddress(const char* func_name) {
    using fn_t = clGetExtensionFunctionAddress_fn_t;
    static fn_t fn = (fn_t)resolve("clGetExtensionFunctionAddress");
    if (!fn) return (void*)0;
    return fn(func_name);
}

typedef cl_command_queue (CL_API_CALL *clCreateCommandQueue_fn_t)(cl_context context, cl_device_id device, cl_command_queue_properties properties, cl_int* errcode_ret);
CL_API_ENTRY cl_command_queue CL_API_CALL clCreateCommandQueue(cl_context context, cl_device_id device, cl_command_queue_properties properties, cl_int* errcode_ret) {
    using fn_t = clCreateCommandQueue_fn_t;
    static fn_t fn = (fn_t)resolve("clCreateCommandQueue");
    if (!fn) return (cl_command_queue)0;
    long long t0 = now_ms();
    cl_command_queue q = fn(context, device, properties, errcode_ret);
    __android_log_print(ANDROID_LOG_INFO, TAG,
        "clCreateCommandQueue -> queue=%p elapsed_ms=%lld", (void*)q, now_ms() - t0);
    return q;
}

typedef cl_sampler (CL_API_CALL *clCreateSampler_fn_t)(cl_context context, cl_bool normalized_coords, cl_addressing_mode addressing_mode, cl_filter_mode filter_mode, cl_int* errcode_ret);
CL_API_ENTRY cl_sampler CL_API_CALL clCreateSampler(cl_context context, cl_bool normalized_coords, cl_addressing_mode addressing_mode, cl_filter_mode filter_mode, cl_int* errcode_ret) {
    using fn_t = clCreateSampler_fn_t;
    static fn_t fn = (fn_t)resolve("clCreateSampler");
    if (!fn) return (cl_sampler)0;
    return fn(context, normalized_coords, addressing_mode, filter_mode, errcode_ret);
}

typedef cl_int (CL_API_CALL *clEnqueueTask_fn_t)(cl_command_queue command_queue, cl_kernel kernel, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueTask(cl_command_queue command_queue, cl_kernel kernel, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueTask_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueTask");
    if (!fn) return (cl_int)0;
    return fn(command_queue, kernel, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_mem (CL_API_CALL *clCreateSubBuffer_fn_t)(cl_mem buffer, cl_mem_flags flags, cl_buffer_create_type buffer_create_type, const void* buffer_create_info, cl_int* errcode_ret);
CL_API_ENTRY cl_mem CL_API_CALL clCreateSubBuffer(cl_mem buffer, cl_mem_flags flags, cl_buffer_create_type buffer_create_type, const void* buffer_create_info, cl_int* errcode_ret) {
    using fn_t = clCreateSubBuffer_fn_t;
    static fn_t fn = (fn_t)resolve("clCreateSubBuffer");
    if (!fn) return (cl_mem)0;
    return fn(buffer, flags, buffer_create_type, buffer_create_info, errcode_ret);
}

typedef cl_int (CL_API_CALL *clSetMemObjectDestructorCallback_fn_t)(cl_mem memobj, void (CL_CALLBACK* pfn_notify)(cl_mem memobj, void* user_data), void* user_data);
CL_API_ENTRY cl_int CL_API_CALL clSetMemObjectDestructorCallback(cl_mem memobj, void (CL_CALLBACK* pfn_notify)(cl_mem memobj, void* user_data), void* user_data) {
    using fn_t = clSetMemObjectDestructorCallback_fn_t;
    static fn_t fn = (fn_t)resolve("clSetMemObjectDestructorCallback");
    if (!fn) return (cl_int)0;
    return fn(memobj, pfn_notify, user_data);
}

typedef cl_event (CL_API_CALL *clCreateUserEvent_fn_t)(cl_context context, cl_int* errcode_ret);
CL_API_ENTRY cl_event CL_API_CALL clCreateUserEvent(cl_context context, cl_int* errcode_ret) {
    using fn_t = clCreateUserEvent_fn_t;
    static fn_t fn = (fn_t)resolve("clCreateUserEvent");
    if (!fn) return (cl_event)0;
    return fn(context, errcode_ret);
}

typedef cl_int (CL_API_CALL *clSetUserEventStatus_fn_t)(cl_event event, cl_int execution_status);
CL_API_ENTRY cl_int CL_API_CALL clSetUserEventStatus(cl_event event, cl_int execution_status) {
    using fn_t = clSetUserEventStatus_fn_t;
    static fn_t fn = (fn_t)resolve("clSetUserEventStatus");
    if (!fn) return (cl_int)0;
    return fn(event, execution_status);
}

typedef cl_int (CL_API_CALL *clSetEventCallback_fn_t)(cl_event event, cl_int command_exec_callback_type, void (CL_CALLBACK* pfn_notify)(cl_event event, cl_int event_command_status, void *user_data), void* user_data);
CL_API_ENTRY cl_int CL_API_CALL clSetEventCallback(cl_event event, cl_int command_exec_callback_type, void (CL_CALLBACK* pfn_notify)(cl_event event, cl_int event_command_status, void *user_data), void* user_data) {
    using fn_t = clSetEventCallback_fn_t;
    static fn_t fn = (fn_t)resolve("clSetEventCallback");
    if (!fn) return (cl_int)0;
    return fn(event, command_exec_callback_type, pfn_notify, user_data);
}

typedef cl_int (CL_API_CALL *clEnqueueReadBufferRect_fn_t)(cl_command_queue command_queue, cl_mem buffer, cl_bool blocking_read, const size_t* buffer_origin, const size_t* host_origin, const size_t* region, size_t buffer_row_pitch, size_t buffer_slice_pitch, size_t host_row_pitch, size_t host_slice_pitch, void* ptr, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueReadBufferRect(cl_command_queue command_queue, cl_mem buffer, cl_bool blocking_read, const size_t* buffer_origin, const size_t* host_origin, const size_t* region, size_t buffer_row_pitch, size_t buffer_slice_pitch, size_t host_row_pitch, size_t host_slice_pitch, void* ptr, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueReadBufferRect_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueReadBufferRect");
    if (!fn) return (cl_int)0;
    return fn(command_queue, buffer, blocking_read, buffer_origin, host_origin, region, buffer_row_pitch, buffer_slice_pitch, host_row_pitch, host_slice_pitch, ptr, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clEnqueueWriteBufferRect_fn_t)(cl_command_queue command_queue, cl_mem buffer, cl_bool blocking_write, const size_t* buffer_origin, const size_t* host_origin, const size_t* region, size_t buffer_row_pitch, size_t buffer_slice_pitch, size_t host_row_pitch, size_t host_slice_pitch, const void* ptr, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueWriteBufferRect(cl_command_queue command_queue, cl_mem buffer, cl_bool blocking_write, const size_t* buffer_origin, const size_t* host_origin, const size_t* region, size_t buffer_row_pitch, size_t buffer_slice_pitch, size_t host_row_pitch, size_t host_slice_pitch, const void* ptr, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueWriteBufferRect_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueWriteBufferRect");
    if (!fn) return (cl_int)0;
    return fn(command_queue, buffer, blocking_write, buffer_origin, host_origin, region, buffer_row_pitch, buffer_slice_pitch, host_row_pitch, host_slice_pitch, ptr, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clEnqueueCopyBufferRect_fn_t)(cl_command_queue command_queue, cl_mem src_buffer, cl_mem dst_buffer, const size_t* src_origin, const size_t* dst_origin, const size_t* region, size_t src_row_pitch, size_t src_slice_pitch, size_t dst_row_pitch, size_t dst_slice_pitch, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueCopyBufferRect(cl_command_queue command_queue, cl_mem src_buffer, cl_mem dst_buffer, const size_t* src_origin, const size_t* dst_origin, const size_t* region, size_t src_row_pitch, size_t src_slice_pitch, size_t dst_row_pitch, size_t dst_slice_pitch, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueCopyBufferRect_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueCopyBufferRect");
    if (!fn) return (cl_int)0;
    return fn(command_queue, src_buffer, dst_buffer, src_origin, dst_origin, region, src_row_pitch, src_slice_pitch, dst_row_pitch, dst_slice_pitch, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clCreateSubDevices_fn_t)(cl_device_id in_device, const cl_device_partition_property* properties, cl_uint num_devices, cl_device_id* out_devices, cl_uint* num_devices_ret);
CL_API_ENTRY cl_int CL_API_CALL clCreateSubDevices(cl_device_id in_device, const cl_device_partition_property* properties, cl_uint num_devices, cl_device_id* out_devices, cl_uint* num_devices_ret) {
    using fn_t = clCreateSubDevices_fn_t;
    static fn_t fn = (fn_t)resolve("clCreateSubDevices");
    if (!fn) return (cl_int)0;
    return fn(in_device, properties, num_devices, out_devices, num_devices_ret);
}

typedef cl_int (CL_API_CALL *clRetainDevice_fn_t)(cl_device_id device);
CL_API_ENTRY cl_int CL_API_CALL clRetainDevice(cl_device_id device) {
    using fn_t = clRetainDevice_fn_t;
    static fn_t fn = (fn_t)resolve("clRetainDevice");
    if (!fn) return (cl_int)0;
    return fn(device);
}

typedef cl_int (CL_API_CALL *clReleaseDevice_fn_t)(cl_device_id device);
CL_API_ENTRY cl_int CL_API_CALL clReleaseDevice(cl_device_id device) {
    using fn_t = clReleaseDevice_fn_t;
    static fn_t fn = (fn_t)resolve("clReleaseDevice");
    if (!fn) return (cl_int)0;
    return fn(device);
}

typedef cl_mem (CL_API_CALL *clCreateImage_fn_t)(cl_context context, cl_mem_flags flags, const cl_image_format* image_format, const cl_image_desc* image_desc, void* host_ptr, cl_int* errcode_ret);
CL_API_ENTRY cl_mem CL_API_CALL clCreateImage(cl_context context, cl_mem_flags flags, const cl_image_format* image_format, const cl_image_desc* image_desc, void* host_ptr, cl_int* errcode_ret) {
    using fn_t = clCreateImage_fn_t;
    static fn_t fn = (fn_t)resolve("clCreateImage");
    if (!fn) return (cl_mem)0;
    return fn(context, flags, image_format, image_desc, host_ptr, errcode_ret);
}

typedef cl_program (CL_API_CALL *clCreateProgramWithBuiltInKernels_fn_t)(cl_context context, cl_uint num_devices, const cl_device_id* device_list, const char* kernel_names, cl_int* errcode_ret);
CL_API_ENTRY cl_program CL_API_CALL clCreateProgramWithBuiltInKernels(cl_context context, cl_uint num_devices, const cl_device_id* device_list, const char* kernel_names, cl_int* errcode_ret) {
    using fn_t = clCreateProgramWithBuiltInKernels_fn_t;
    static fn_t fn = (fn_t)resolve("clCreateProgramWithBuiltInKernels");
    if (!fn) return (cl_program)0;
    return fn(context, num_devices, device_list, kernel_names, errcode_ret);
}

typedef cl_int (CL_API_CALL *clCompileProgram_fn_t)(cl_program program, cl_uint num_devices, const cl_device_id* device_list, const char* options, cl_uint num_input_headers, const cl_program* input_headers, const char** header_include_names, void (CL_CALLBACK* pfn_notify)(cl_program program, void* user_data), void* user_data);
CL_API_ENTRY cl_int CL_API_CALL clCompileProgram(cl_program program, cl_uint num_devices, const cl_device_id* device_list, const char* options, cl_uint num_input_headers, const cl_program* input_headers, const char** header_include_names, void (CL_CALLBACK* pfn_notify)(cl_program program, void* user_data), void* user_data) {
    using fn_t = clCompileProgram_fn_t;
    static fn_t fn = (fn_t)resolve("clCompileProgram");
    if (!fn) return (cl_int)0;
    return fn(program, num_devices, device_list, options, num_input_headers, input_headers, header_include_names, pfn_notify, user_data);
}

typedef cl_program (CL_API_CALL *clLinkProgram_fn_t)(cl_context context, cl_uint num_devices, const cl_device_id* device_list, const char* options, cl_uint num_input_programs, const cl_program* input_programs, void (CL_CALLBACK* pfn_notify)(cl_program program, void* user_data), void* user_data, cl_int* errcode_ret);
CL_API_ENTRY cl_program CL_API_CALL clLinkProgram(cl_context context, cl_uint num_devices, const cl_device_id* device_list, const char* options, cl_uint num_input_programs, const cl_program* input_programs, void (CL_CALLBACK* pfn_notify)(cl_program program, void* user_data), void* user_data, cl_int* errcode_ret) {
    using fn_t = clLinkProgram_fn_t;
    static fn_t fn = (fn_t)resolve("clLinkProgram");
    if (!fn) return (cl_program)0;
    return fn(context, num_devices, device_list, options, num_input_programs, input_programs, pfn_notify, user_data, errcode_ret);
}

typedef cl_int (CL_API_CALL *clUnloadPlatformCompiler_fn_t)(cl_platform_id platform);
CL_API_ENTRY cl_int CL_API_CALL clUnloadPlatformCompiler(cl_platform_id platform) {
    using fn_t = clUnloadPlatformCompiler_fn_t;
    static fn_t fn = (fn_t)resolve("clUnloadPlatformCompiler");
    if (!fn) return (cl_int)0;
    return fn(platform);
}

typedef cl_int (CL_API_CALL *clGetKernelArgInfo_fn_t)(cl_kernel kernel, cl_uint arg_index, cl_kernel_arg_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret);
CL_API_ENTRY cl_int CL_API_CALL clGetKernelArgInfo(cl_kernel kernel, cl_uint arg_index, cl_kernel_arg_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret) {
    using fn_t = clGetKernelArgInfo_fn_t;
    static fn_t fn = (fn_t)resolve("clGetKernelArgInfo");
    if (!fn) return (cl_int)0;
    return fn(kernel, arg_index, param_name, param_value_size, param_value, param_value_size_ret);
}

typedef cl_int (CL_API_CALL *clEnqueueFillBuffer_fn_t)(cl_command_queue command_queue, cl_mem buffer, const void* pattern, size_t pattern_size, size_t offset, size_t size, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueFillBuffer(cl_command_queue command_queue, cl_mem buffer, const void* pattern, size_t pattern_size, size_t offset, size_t size, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueFillBuffer_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueFillBuffer");
    if (!fn) return (cl_int)0;
    return fn(command_queue, buffer, pattern, pattern_size, offset, size, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clEnqueueFillImage_fn_t)(cl_command_queue command_queue, cl_mem image, const void* fill_color, const size_t* origin, const size_t* region, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueFillImage(cl_command_queue command_queue, cl_mem image, const void* fill_color, const size_t* origin, const size_t* region, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueFillImage_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueFillImage");
    if (!fn) return (cl_int)0;
    return fn(command_queue, image, fill_color, origin, region, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clEnqueueMigrateMemObjects_fn_t)(cl_command_queue command_queue, cl_uint num_mem_objects, const cl_mem* mem_objects, cl_mem_migration_flags flags, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueMigrateMemObjects(cl_command_queue command_queue, cl_uint num_mem_objects, const cl_mem* mem_objects, cl_mem_migration_flags flags, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueMigrateMemObjects_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueMigrateMemObjects");
    if (!fn) return (cl_int)0;
    return fn(command_queue, num_mem_objects, mem_objects, flags, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clEnqueueMarkerWithWaitList_fn_t)(cl_command_queue command_queue, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueMarkerWithWaitList(cl_command_queue command_queue, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueMarkerWithWaitList_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueMarkerWithWaitList");
    if (!fn) return (cl_int)0;
    return fn(command_queue, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clEnqueueBarrierWithWaitList_fn_t)(cl_command_queue command_queue, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueBarrierWithWaitList(cl_command_queue command_queue, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueBarrierWithWaitList_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueBarrierWithWaitList");
    if (!fn) return (cl_int)0;
    return fn(command_queue, num_events_in_wait_list, event_wait_list, event);
}

typedef void* (CL_API_CALL *clGetExtensionFunctionAddressForPlatform_fn_t)(cl_platform_id platform, const char* func_name);
CL_API_ENTRY void* CL_API_CALL clGetExtensionFunctionAddressForPlatform(cl_platform_id platform, const char* func_name) {
    using fn_t = clGetExtensionFunctionAddressForPlatform_fn_t;
    static fn_t fn = (fn_t)resolve("clGetExtensionFunctionAddressForPlatform");
    if (!fn) return (void*)0;
    return fn(platform, func_name);
}

typedef cl_command_queue (CL_API_CALL *clCreateCommandQueueWithProperties_fn_t)(cl_context context, cl_device_id device, const cl_queue_properties* properties, cl_int* errcode_ret);
CL_API_ENTRY cl_command_queue CL_API_CALL clCreateCommandQueueWithProperties(cl_context context, cl_device_id device, const cl_queue_properties* properties, cl_int* errcode_ret) {
    using fn_t = clCreateCommandQueueWithProperties_fn_t;
    static fn_t fn = (fn_t)resolve("clCreateCommandQueueWithProperties");
    if (!fn) return (cl_command_queue)0;
    long long t0 = now_ms();
    cl_command_queue q = fn(context, device, properties, errcode_ret);
    __android_log_print(ANDROID_LOG_INFO, TAG,
        "clCreateCommandQueueWithProperties -> queue=%p elapsed_ms=%lld", (void*)q, now_ms() - t0);
    return q;
}

typedef cl_mem (CL_API_CALL *clCreatePipe_fn_t)(cl_context context, cl_mem_flags flags, cl_uint pipe_packet_size, cl_uint pipe_max_packets, const cl_pipe_properties* properties, cl_int* errcode_ret);
CL_API_ENTRY cl_mem CL_API_CALL clCreatePipe(cl_context context, cl_mem_flags flags, cl_uint pipe_packet_size, cl_uint pipe_max_packets, const cl_pipe_properties* properties, cl_int* errcode_ret) {
    using fn_t = clCreatePipe_fn_t;
    static fn_t fn = (fn_t)resolve("clCreatePipe");
    if (!fn) return (cl_mem)0;
    return fn(context, flags, pipe_packet_size, pipe_max_packets, properties, errcode_ret);
}

typedef cl_int (CL_API_CALL *clGetPipeInfo_fn_t)(cl_mem pipe, cl_pipe_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret);
CL_API_ENTRY cl_int CL_API_CALL clGetPipeInfo(cl_mem pipe, cl_pipe_info param_name, size_t param_value_size, void* param_value, size_t* param_value_size_ret) {
    using fn_t = clGetPipeInfo_fn_t;
    static fn_t fn = (fn_t)resolve("clGetPipeInfo");
    if (!fn) return (cl_int)0;
    return fn(pipe, param_name, param_value_size, param_value, param_value_size_ret);
}

typedef void* (CL_API_CALL *clSVMAlloc_fn_t)(cl_context context, cl_svm_mem_flags flags, size_t size, cl_uint alignment);
CL_API_ENTRY void* CL_API_CALL clSVMAlloc(cl_context context, cl_svm_mem_flags flags, size_t size, cl_uint alignment) {
    using fn_t = clSVMAlloc_fn_t;
    static fn_t fn = (fn_t)resolve("clSVMAlloc");
    if (!fn) return (void*)0;
    return fn(context, flags, size, alignment);
}

typedef void (CL_API_CALL *clSVMFree_fn_t)(cl_context context, void* svm_pointer);
CL_API_ENTRY void CL_API_CALL clSVMFree(cl_context context, void* svm_pointer) {
    using fn_t = clSVMFree_fn_t;
    static fn_t fn = (fn_t)resolve("clSVMFree");
    if (!fn) return;
    fn(context, svm_pointer);
}

typedef cl_sampler (CL_API_CALL *clCreateSamplerWithProperties_fn_t)(cl_context context, const cl_sampler_properties* sampler_properties, cl_int* errcode_ret);
CL_API_ENTRY cl_sampler CL_API_CALL clCreateSamplerWithProperties(cl_context context, const cl_sampler_properties* sampler_properties, cl_int* errcode_ret) {
    using fn_t = clCreateSamplerWithProperties_fn_t;
    static fn_t fn = (fn_t)resolve("clCreateSamplerWithProperties");
    if (!fn) return (cl_sampler)0;
    return fn(context, sampler_properties, errcode_ret);
}

typedef cl_int (CL_API_CALL *clSetKernelArgSVMPointer_fn_t)(cl_kernel kernel, cl_uint arg_index, const void* arg_value);
CL_API_ENTRY cl_int CL_API_CALL clSetKernelArgSVMPointer(cl_kernel kernel, cl_uint arg_index, const void* arg_value) {
    using fn_t = clSetKernelArgSVMPointer_fn_t;
    static fn_t fn = (fn_t)resolve("clSetKernelArgSVMPointer");
    if (!fn) return (cl_int)0;
    return fn(kernel, arg_index, arg_value);
}

typedef cl_int (CL_API_CALL *clSetKernelExecInfo_fn_t)(cl_kernel kernel, cl_kernel_exec_info param_name, size_t param_value_size, const void* param_value);
CL_API_ENTRY cl_int CL_API_CALL clSetKernelExecInfo(cl_kernel kernel, cl_kernel_exec_info param_name, size_t param_value_size, const void* param_value) {
    using fn_t = clSetKernelExecInfo_fn_t;
    static fn_t fn = (fn_t)resolve("clSetKernelExecInfo");
    if (!fn) return (cl_int)0;
    return fn(kernel, param_name, param_value_size, param_value);
}

typedef cl_int (CL_API_CALL *clEnqueueSVMFree_fn_t)(cl_command_queue command_queue, cl_uint num_svm_pointers, void* svm_pointers[], void (CL_CALLBACK* pfn_free_func)(cl_command_queue queue, cl_uint num_svm_pointers, void* svm_pointers[], void* user_data), void* user_data, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueSVMFree(cl_command_queue command_queue, cl_uint num_svm_pointers, void* svm_pointers[], void (CL_CALLBACK* pfn_free_func)(cl_command_queue queue, cl_uint num_svm_pointers, void* svm_pointers[], void* user_data), void* user_data, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueSVMFree_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueSVMFree");
    if (!fn) return (cl_int)0;
    return fn(command_queue, num_svm_pointers, svm_pointers, pfn_free_func, user_data, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clEnqueueSVMMemcpy_fn_t)(cl_command_queue command_queue, cl_bool blocking_copy, void* dst_ptr, const void* src_ptr, size_t size, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueSVMMemcpy(cl_command_queue command_queue, cl_bool blocking_copy, void* dst_ptr, const void* src_ptr, size_t size, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueSVMMemcpy_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueSVMMemcpy");
    if (!fn) return (cl_int)0;
    return fn(command_queue, blocking_copy, dst_ptr, src_ptr, size, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clEnqueueSVMMemFill_fn_t)(cl_command_queue command_queue, void* svm_ptr, const void* pattern, size_t pattern_size, size_t size, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueSVMMemFill(cl_command_queue command_queue, void* svm_ptr, const void* pattern, size_t pattern_size, size_t size, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueSVMMemFill_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueSVMMemFill");
    if (!fn) return (cl_int)0;
    return fn(command_queue, svm_ptr, pattern, pattern_size, size, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clEnqueueSVMMap_fn_t)(cl_command_queue command_queue, cl_bool blocking_map, cl_map_flags flags, void* svm_ptr, size_t size, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueSVMMap(cl_command_queue command_queue, cl_bool blocking_map, cl_map_flags flags, void* svm_ptr, size_t size, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueSVMMap_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueSVMMap");
    if (!fn) return (cl_int)0;
    return fn(command_queue, blocking_map, flags, svm_ptr, size, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clEnqueueSVMUnmap_fn_t)(cl_command_queue command_queue, void* svm_ptr, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueSVMUnmap(cl_command_queue command_queue, void* svm_ptr, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueSVMUnmap_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueSVMUnmap");
    if (!fn) return (cl_int)0;
    return fn(command_queue, svm_ptr, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clSetDefaultDeviceCommandQueue_fn_t)(cl_context context, cl_device_id device, cl_command_queue command_queue);
CL_API_ENTRY cl_int CL_API_CALL clSetDefaultDeviceCommandQueue(cl_context context, cl_device_id device, cl_command_queue command_queue) {
    using fn_t = clSetDefaultDeviceCommandQueue_fn_t;
    static fn_t fn = (fn_t)resolve("clSetDefaultDeviceCommandQueue");
    if (!fn) return (cl_int)0;
    return fn(context, device, command_queue);
}

typedef cl_int (CL_API_CALL *clGetDeviceAndHostTimer_fn_t)(cl_device_id device, cl_ulong* device_timestamp, cl_ulong* host_timestamp);
CL_API_ENTRY cl_int CL_API_CALL clGetDeviceAndHostTimer(cl_device_id device, cl_ulong* device_timestamp, cl_ulong* host_timestamp) {
    using fn_t = clGetDeviceAndHostTimer_fn_t;
    static fn_t fn = (fn_t)resolve("clGetDeviceAndHostTimer");
    if (!fn) return (cl_int)0;
    return fn(device, device_timestamp, host_timestamp);
}

typedef cl_int (CL_API_CALL *clGetHostTimer_fn_t)(cl_device_id device, cl_ulong* host_timestamp);
CL_API_ENTRY cl_int CL_API_CALL clGetHostTimer(cl_device_id device, cl_ulong* host_timestamp) {
    using fn_t = clGetHostTimer_fn_t;
    static fn_t fn = (fn_t)resolve("clGetHostTimer");
    if (!fn) return (cl_int)0;
    return fn(device, host_timestamp);
}

typedef cl_program (CL_API_CALL *clCreateProgramWithIL_fn_t)(cl_context context, const void* il, size_t length, cl_int* errcode_ret);
CL_API_ENTRY cl_program CL_API_CALL clCreateProgramWithIL(cl_context context, const void* il, size_t length, cl_int* errcode_ret) {
    using fn_t = clCreateProgramWithIL_fn_t;
    static fn_t fn = (fn_t)resolve("clCreateProgramWithIL");
    if (!fn) return (cl_program)0;
    return fn(context, il, length, errcode_ret);
}

typedef cl_kernel (CL_API_CALL *clCloneKernel_fn_t)(cl_kernel source_kernel, cl_int* errcode_ret);
CL_API_ENTRY cl_kernel CL_API_CALL clCloneKernel(cl_kernel source_kernel, cl_int* errcode_ret) {
    using fn_t = clCloneKernel_fn_t;
    static fn_t fn = (fn_t)resolve("clCloneKernel");
    if (!fn) return (cl_kernel)0;
    return fn(source_kernel, errcode_ret);
}

typedef cl_int (CL_API_CALL *clGetKernelSubGroupInfo_fn_t)(cl_kernel kernel, cl_device_id device, cl_kernel_sub_group_info param_name, size_t input_value_size, const void* input_value, size_t param_value_size, void* param_value, size_t* param_value_size_ret);
CL_API_ENTRY cl_int CL_API_CALL clGetKernelSubGroupInfo(cl_kernel kernel, cl_device_id device, cl_kernel_sub_group_info param_name, size_t input_value_size, const void* input_value, size_t param_value_size, void* param_value, size_t* param_value_size_ret) {
    using fn_t = clGetKernelSubGroupInfo_fn_t;
    static fn_t fn = (fn_t)resolve("clGetKernelSubGroupInfo");
    if (!fn) return (cl_int)0;
    return fn(kernel, device, param_name, input_value_size, input_value, param_value_size, param_value, param_value_size_ret);
}

typedef cl_int (CL_API_CALL *clEnqueueSVMMigrateMem_fn_t)(cl_command_queue command_queue, cl_uint num_svm_pointers, const void** svm_pointers, const size_t* sizes, cl_mem_migration_flags flags, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueSVMMigrateMem(cl_command_queue command_queue, cl_uint num_svm_pointers, const void** svm_pointers, const size_t* sizes, cl_mem_migration_flags flags, cl_uint num_events_in_wait_list, const cl_event* event_wait_list, cl_event* event) {
    using fn_t = clEnqueueSVMMigrateMem_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueSVMMigrateMem");
    if (!fn) return (cl_int)0;
    return fn(command_queue, num_svm_pointers, svm_pointers, sizes, flags, num_events_in_wait_list, event_wait_list, event);
}

typedef cl_int (CL_API_CALL *clSetProgramSpecializationConstant_fn_t)(cl_program program, cl_uint spec_id, size_t spec_size, const void* spec_value);
CL_API_ENTRY cl_int CL_API_CALL clSetProgramSpecializationConstant(cl_program program, cl_uint spec_id, size_t spec_size, const void* spec_value) {
    using fn_t = clSetProgramSpecializationConstant_fn_t;
    static fn_t fn = (fn_t)resolve("clSetProgramSpecializationConstant");
    if (!fn) return (cl_int)0;
    return fn(program, spec_id, spec_size, spec_value);
}

typedef cl_int (CL_API_CALL *clSetProgramReleaseCallback_fn_t)(cl_program program, void (CL_CALLBACK* pfn_notify)(cl_program program, void* user_data), void* user_data);
CL_API_ENTRY cl_int CL_API_CALL clSetProgramReleaseCallback(cl_program program, void (CL_CALLBACK* pfn_notify)(cl_program program, void* user_data), void* user_data) {
    using fn_t = clSetProgramReleaseCallback_fn_t;
    static fn_t fn = (fn_t)resolve("clSetProgramReleaseCallback");
    if (!fn) return (cl_int)0;
    return fn(program, pfn_notify, user_data);
}

typedef cl_int (CL_API_CALL *clSetContextDestructorCallback_fn_t)(cl_context context, void (CL_CALLBACK* pfn_notify)(cl_context context, void* user_data), void* user_data);
CL_API_ENTRY cl_int CL_API_CALL clSetContextDestructorCallback(cl_context context, void (CL_CALLBACK* pfn_notify)(cl_context context, void* user_data), void* user_data) {
    using fn_t = clSetContextDestructorCallback_fn_t;
    static fn_t fn = (fn_t)resolve("clSetContextDestructorCallback");
    if (!fn) return (cl_int)0;
    return fn(context, pfn_notify, user_data);
}

typedef cl_mem (CL_API_CALL *clCreateBufferWithProperties_fn_t)(cl_context context, const cl_mem_properties* properties, cl_mem_flags flags, size_t size, void* host_ptr, cl_int* errcode_ret);
CL_API_ENTRY cl_mem CL_API_CALL clCreateBufferWithProperties(cl_context context, const cl_mem_properties* properties, cl_mem_flags flags, size_t size, void* host_ptr, cl_int* errcode_ret) {
    using fn_t = clCreateBufferWithProperties_fn_t;
    static fn_t fn = (fn_t)resolve("clCreateBufferWithProperties");
    if (!fn) return (cl_mem)0;
    return fn(context, properties, flags, size, host_ptr, errcode_ret);
}

typedef cl_mem (CL_API_CALL *clCreateImageWithProperties_fn_t)(cl_context context, const cl_mem_properties* properties, cl_mem_flags flags, const cl_image_format* image_format, const cl_image_desc* image_desc, void* host_ptr, cl_int* errcode_ret);
CL_API_ENTRY cl_mem CL_API_CALL clCreateImageWithProperties(cl_context context, const cl_mem_properties* properties, cl_mem_flags flags, const cl_image_format* image_format, const cl_image_desc* image_desc, void* host_ptr, cl_int* errcode_ret) {
    using fn_t = clCreateImageWithProperties_fn_t;
    static fn_t fn = (fn_t)resolve("clCreateImageWithProperties");
    if (!fn) return (cl_mem)0;
    return fn(context, properties, flags, image_format, image_desc, host_ptr, errcode_ret);
}

typedef cl_int (CL_API_CALL *clEnqueueXNDRangeKernelQCOM_fn_t)(cl_command_queue command_queue, cl_kernel kernel, cl_uint work_dim, size_t const* global_work_offset, size_t  const* global_work_size, size_t  const* local_work_size, const void** xIBData, const cl_uint* xIBSizes, cl_event* event);
CL_API_ENTRY cl_int CL_API_CALL clEnqueueXNDRangeKernelQCOM(cl_command_queue command_queue, cl_kernel kernel, cl_uint work_dim, size_t const* global_work_offset, size_t  const* global_work_size, size_t  const* local_work_size, const void** xIBData, const cl_uint* xIBSizes, cl_event* event) {
    using fn_t = clEnqueueXNDRangeKernelQCOM_fn_t;
    static fn_t fn = (fn_t)resolve("clEnqueueXNDRangeKernelQCOM");
    if (!fn) return (cl_int)0;
    return fn(command_queue, kernel, work_dim, global_work_offset, global_work_size, local_work_size, xIBData, xIBSizes, event);
}

typedef void* (CL_API_CALL *clDataExtensionQCOM_fn_t)(cl_context context, cl_uint num_devices, cl_device_id  const* device_list, cl_command_queue queue, cl_uint num_data, size_t const* lengths, const void** data, cl_int* statuses, cl_int* errcode_ret);
CL_API_ENTRY void* CL_API_CALL clDataExtensionQCOM(cl_context context, cl_uint num_devices, cl_device_id  const* device_list, cl_command_queue queue, cl_uint num_data, size_t const* lengths, const void** data, cl_int* statuses, cl_int* errcode_ret) {
    using fn_t = clDataExtensionQCOM_fn_t;
    static fn_t fn = (fn_t)resolve("clDataExtensionQCOM");
    if (!fn) return (void*)0;
    return fn(context, num_devices, device_list, queue, num_data, lengths, data, statuses, errcode_ret);
}

typedef cl_int (CL_API_CALL *clEventWaitForSubmissionQCOM_fn_t)(cl_event event);
CL_API_ENTRY cl_int CL_API_CALL clEventWaitForSubmissionQCOM(cl_event event) {
    using fn_t = clEventWaitForSubmissionQCOM_fn_t;
    static fn_t fn = (fn_t)resolve("clEventWaitForSubmissionQCOM");
    if (!fn) return (cl_int)0;
    return fn(event);
}

typedef cl_int (CL_API_CALL *clGetMLInterfaceQCOM_fn_t)(void* pInterface, cl_int majorVersion, cl_int minorVersion);
CL_API_ENTRY cl_int CL_API_CALL clGetMLInterfaceQCOM(void* pInterface, cl_int majorVersion, cl_int minorVersion) {
    using fn_t = clGetMLInterfaceQCOM_fn_t;
    static fn_t fn = (fn_t)resolve("clGetMLInterfaceQCOM");
    if (!fn) return (cl_int)0;
    return fn(pInterface, majorVersion, minorVersion);
}

typedef cl_int (CL_API_CALL *clQueryMLInterfaceVersionsQCOM_fn_t)(cl_int* pMajorVersions, cl_int* pMinorVersions, cl_uint numVersions, cl_uint* pNumVersionsRet);
CL_API_ENTRY cl_int CL_API_CALL clQueryMLInterfaceVersionsQCOM(cl_int* pMajorVersions, cl_int* pMinorVersions, cl_uint numVersions, cl_uint* pNumVersionsRet) {
    using fn_t = clQueryMLInterfaceVersionsQCOM_fn_t;
    static fn_t fn = (fn_t)resolve("clQueryMLInterfaceVersionsQCOM");
    if (!fn) return (cl_int)0;
    return fn(pMajorVersions, pMinorVersions, numVersions, pNumVersionsRet);
}

} // extern "C"
